version: '3.7'

services:

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq_server 
    expose:
      - "5672"
      - "15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 5s
      retries: 3

  fastapi:
    image: fastapitest 
    container_name: fastapi_pika_test 
    ports:
      - 8000:80
    command: bash -c "cd app; sleep 10; uvicorn main:app --host 0.0.0.0 --port 80 --reload --log-level critical --use-colors"
    depends_on:
      - rabbitmq

  worker:
    image: fastapitest
    command: bash -c "sleep 15; python app/receive.py"
    container_name: pika_worker
    restart: on-failure
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq 

